/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import clases.Usuario;
import clases.documento;
import javax.swing.JOptionPane;
import org.graphstream.graph.Graph;
import org.graphstream.graph.Node;
import org.graphstream.graph.implementations.SingleGraph;
import org.graphstream.ui.spriteManager.SpriteManager;
import org.graphstream.ui.view.Viewer;

/**
 *
 * @author miwindowspc
 */
public class InterfazGrafica extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InterfazGrafica.class.getName());
    private LogicaInterfaz logica = new LogicaInterfaz();
    /**
     * Creates new form InterfazGrafica
     */
    public InterfazGrafica() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonMostrarCola = new javax.swing.JButton();
        botonAddUser = new javax.swing.JButton();
        botonMostrarUser = new javax.swing.JButton();
        botonAnadirDoc = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        output = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botonMostrarCola.setText("Mostrar Cola");
        botonMostrarCola.addActionListener(this::botonMostrarColaActionPerformed);

        botonAddUser.setText("Añadir Usuario");
        botonAddUser.addActionListener(this::botonAddUserActionPerformed);

        botonMostrarUser.setText("Mostrar Users");
        botonMostrarUser.addActionListener(this::botonMostrarUserActionPerformed);

        botonAnadirDoc.setText("Añadir Documento");
        botonAnadirDoc.addActionListener(this::botonAnadirDocActionPerformed);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setText("Pila de Impresión");

        output.setColumns(20);
        output.setRows(5);
        jScrollPane1.setViewportView(output);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(botonMostrarCola, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonMostrarUser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonAddUser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonAnadirDoc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addComponent(botonMostrarCola)
                .addGap(21, 21, 21)
                .addComponent(botonMostrarUser)
                .addGap(18, 18, 18)
                .addComponent(botonAddUser)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(botonAnadirDoc)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonMostrarColaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMostrarColaActionPerformed
        logica.mostrarVentanaCola();
    }//GEN-LAST:event_botonMostrarColaActionPerformed

    private void botonAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAddUserActionPerformed
        String nombre = JOptionPane.showInputDialog(this, "Nombre del usuario:");
        String[] opciones = {"Prioridad Alta", "Prioridad Media", "Prioridad Baja"};
        int seleccion = JOptionPane.showOptionDialog(this,
            "¿Qué prioridad desea que tenga este usuario?",
            "Escoger Prioridad",
            JOptionPane.DEFAULT_OPTION,
            JOptionPane.QUESTION_MESSAGE,
            null,
            opciones,
             opciones[0]);
        
        String prioridad = "";
        switch (seleccion) { 
            case 0:
                {
                  prioridad = "prioridad_alta";
                  break;
                }
            
            case 1:
                {
                  prioridad = "prioridad_media";  
                  break;
                }
                
            case 2:
                {
                  prioridad = "prioridad_baja";
                  break;
                }
        }
        Usuario nuevo = new Usuario(nombre, prioridad);
        //PARA AÑADIR: LÓGICA DE GUARDAR
        logica.AñadirUsuarioUI(nuevo);
    }//GEN-LAST:event_botonAddUserActionPerformed

    private void botonMostrarUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMostrarUserActionPerformed
       logica.mostrarVentanaUser();
    }//GEN-LAST:event_botonMostrarUserActionPerformed

    private void botonAnadirDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAnadirDocActionPerformed
        //FALTA: integrar logica de guardado
        //FALTA: integrar logica de tabla de hash
        String username = JOptionPane.showInputDialog(this, "Nombre del usuario:");
        String docname = JOptionPane.showInputDialog(this, "Nombre del documento:");
        String paginasS = JOptionPane.showInputDialog(this, "Cantidad de paginas:");
        if(paginasS.matches("^[0-9]*$") && paginasS.length() > 1){
            int paginas = Integer.parseInt(paginasS);
            String[] opciones = {"Prioridad Alta", "Prioridad Media", "Prioridad Baja"};
            int seleccion = JOptionPane.showOptionDialog(this,
                "¿Qué prioridad desea que tenga este usuario?",
                "Escoger Prioridad",
                JOptionPane.DEFAULT_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                opciones,
                 opciones[0]);

            String prioridad = "";
            switch (seleccion) { 
                case 0:
                    {
                      prioridad = "prioridad_alta";
                      break;
                    }

                case 1:
                    {
                      prioridad = "prioridad_media";  
                      break;
                    }

                case 2:
                    {
                      prioridad = "prioridad_baja";
                      break;
                    }
            }
            documento doc = new documento(docname, paginas, prioridad, false);
            Usuario usertest = new Usuario(username, prioridad); //SE DEBE QUITAR ESTO DESPUES DE IMPLEMENTAR ESTADOS DE GUARTADO!!
            logica.AnadirDocumentoUser(usertest, doc); 
        }
        else
        {
            javax.swing.JOptionPane.showMessageDialog(null,
                "Eso no es un numero valido.",
                "ERROR",
                javax.swing.JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_botonAnadirDocActionPerformed
}
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new InterfazGrafica().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAddUser;
    private javax.swing.JButton botonAnadirDoc;
    private javax.swing.JButton botonMostrarCola;
    private javax.swing.JButton botonMostrarUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea output;
    // End of variables declaration//GEN-END:variables
}
