package interfaznew;

import clases.Usuario;
import primitivas.GuardadoCSV;
import clases.documento;
import javax.swing.JOptionPane;
import org.graphstream.graph.Graph;
import org.graphstream.graph.Node;
import org.graphstream.graph.implementations.SingleGraph;
import org.graphstream.ui.spriteManager.SpriteManager;
import org.graphstream.ui.view.Viewer;
import proyecto2edd.Proyecto2EDD;
import primitivas.Normalizador;

/**
 *
 * @author miwindowspc
 */
public class InterfazGrafica extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InterfazGrafica.class.getName());
    private Proyecto2EDD motor;
    private LogicaInterfaz logica;

    /**
     * Creates new form InterfazGrafica
     */
    public InterfazGrafica() {
        this.motor = new Proyecto2EDD();
        this.logica = new LogicaInterfaz(this, this.motor);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonMostrarCola = new javax.swing.JButton();
        botonAddUser = new javax.swing.JButton();
        botonMostrarUser = new javax.swing.JButton();
        botonAnadirDoc = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        output = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        botonEliminarDocumento = new javax.swing.JButton();
        botonEliminarUsuario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botonMostrarCola.setText("Mostrar Cola");
        botonMostrarCola.addActionListener(this::botonMostrarColaActionPerformed);

        botonAddUser.setText("Añadir Usuario");
        botonAddUser.addActionListener(this::botonAddUserActionPerformed);

        botonMostrarUser.setText("Mostrar Users");
        botonMostrarUser.addActionListener(this::botonMostrarUserActionPerformed);

        botonAnadirDoc.setText("Añadir Documento");
        botonAnadirDoc.addActionListener(this::botonAnadirDocActionPerformed);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setText("Pila de Impresión");

        output.setColumns(20);
        output.setRows(5);
        jScrollPane1.setViewportView(output);

        jButton1.setText("Cargar CSV");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("Guardar CSV");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        botonEliminarDocumento.setText("Eliminar Documento");
        botonEliminarDocumento.addActionListener(this::botonEliminarDocumentoActionPerformed);

        botonEliminarUsuario.setText("Eliminar Usuario");
        botonEliminarUsuario.addActionListener(this::botonEliminarUsuarioActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(botonMostrarCola, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botonMostrarUser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE))
                            .addComponent(jButton1)
                            .addComponent(jButton2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonAnadirDoc)
                            .addComponent(botonAddUser, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonEliminarDocumento))))
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonEliminarUsuario)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(botonMostrarCola)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonAddUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonAnadirDoc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonMostrarUser)
                        .addGap(100, 100, 100)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addContainerGap(12, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(botonEliminarDocumento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonEliminarUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonMostrarColaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMostrarColaActionPerformed
        logica.mostrarVentanaCola();
    }//GEN-LAST:event_botonMostrarColaActionPerformed

    private void botonAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAddUserActionPerformed
        String nombre = JOptionPane.showInputDialog(this, "Nombre del usuario:");
        if (nombre != null && !nombre.trim().isEmpty()) {
            nombre = Normalizador.NormalizarTexto(nombre);
            String[] opciones = {"Prioridad Alta", "Prioridad Media", "Prioridad Baja"};
            int seleccion = JOptionPane.showOptionDialog(this,
                    "¿Qué prioridad desea que tenga este usuario?",
                    "Escoger Prioridad",
                    JOptionPane.DEFAULT_OPTION,
                    JOptionPane.QUESTION_MESSAGE,
                    null,
                    opciones,
                    opciones[0]);

            String prioridad = "";
            switch (seleccion) {
                case 0: {
                    prioridad = "prioridad_alta";
                    break;
                }

                case 1: {
                    prioridad = "prioridad_media";
                    break;
                }

                case 2: {
                    prioridad = "prioridad_baja";
                    break;
                }
                default: {
                    return;
                }
            }
            boolean exito = logica.intentarRegistrarUsuario(nombre, prioridad);
            if (exito) {
                Usuario nuevo = new Usuario(nombre, prioridad);
                logica.AñadirUsuarioUI(nuevo);
                updateConsola("✓ Usuario '" + nombre + "' añadido correctamente.\n");
                JOptionPane.showMessageDialog(this, "Usuario registrado con éxito.");
            } else {
                updateConsola("✗ Error: El usuario '" + nombre + "' ya existe en el sistema.\n");
                JOptionPane.showMessageDialog(this, "Ese usuario ya existe.", "Error de Duplicado", JOptionPane.WARNING_MESSAGE);
            }
        }
        else
        {
           updateConsola("✗ Error: No puede poner un nombre vacio a un usuario.");
           JOptionPane.showMessageDialog(this, "No puede pasar un usuario vacio.", "Error de Nombre", JOptionPane.WARNING_MESSAGE); 
        }
    }//GEN-LAST:event_botonAddUserActionPerformed

    private void botonMostrarUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMostrarUserActionPerformed
        logica.mostrarVentanaUser();
    }//GEN-LAST:event_botonMostrarUserActionPerformed

    private void botonAnadirDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAnadirDocActionPerformed
        //FALTA: integrar logica de guardado
        String username = JOptionPane.showInputDialog(this, "Nombre del usuario:");
        if (username == null) { //se añade esto por si acaso el usuario escapa
            return;
        }
        username = Normalizador.NormalizarTexto(username);
        Usuario usuarioExistente = (Usuario) logica.getUsuariosLocal().get(username);

        if (usuarioExistente == null) {
            JOptionPane.showMessageDialog(this, "Error: El usuario '" + username + "' no existe.", "Usuario no encontrado", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String docname = JOptionPane.showInputDialog(this, "Nombre del documento:");
        docname = Normalizador.NormalizarTexto(docname);
        if (usuarioExistente.buscar(docname) == null){
            String paginasS = JOptionPane.showInputDialog(this, "Cantidad de paginas:");

            if (paginasS != null) {
                if (paginasS.matches("^[0-9]*$") && !paginasS.isEmpty()) { //se revisa si el string tiene los numeros validos y si no esta vacio
                    int paginas = Integer.parseInt(paginasS);
                    if (paginas > 0) { //luego se verifica si la cantidad de paginas es mayor a 0
                        String tipo = JOptionPane.showInputDialog(this, "Tipo de documento:");
                        documento doc = new documento(docname, paginas, tipo, false);
                        logica.AnadirDocumentoUser(username, doc);
                    } else {
                        JOptionPane.showMessageDialog(this, "La cantidad de páginas debe ser mayor a 0.", "ERROR", JOptionPane.ERROR_MESSAGE);
                        updateConsola("✗ Error al añadir documento: La cantidad de paginas debe ser mayor a 0.\n");
                    }
                } else {
                    javax.swing.JOptionPane.showMessageDialog(null,
                            "Eso no es un numero valido.",
                            "ERROR",
                            javax.swing.JOptionPane.ERROR_MESSAGE);
                    updateConsola("✗ Error al añadir documento: El numero de paginas no es valido.\n");
                }
            } else {
                javax.swing.JOptionPane.showMessageDialog(null,
                        "No insertaste un nombre al documento.",
                        "ERROR",
                        javax.swing.JOptionPane.ERROR_MESSAGE);
                updateConsola("✗ Error al añadir documento: No se inserto un nombre.\n");
            }
        }
        else{
            javax.swing.JOptionPane.showMessageDialog(null,
                        "Ese documento ya existe.",
                        "ERROR",
                        javax.swing.JOptionPane.ERROR_MESSAGE);
            updateConsola("✗ Error al añadir documento: Ya existe ese documento.\n");
        }
    }//GEN-LAST:event_botonAnadirDocActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        boolean exito = logica.guardarUsuariosEnCSV();
        if (exito) {
            updateConsola("✓ Usuarios guardados exitosamente en CSV\n");
        } else {
            updateConsola("✗ Error al guardar CSV\n");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        boolean exito = logica.guardarUsuariosEnCSV();
        if (exito) {
            updateConsola("✓ Usuarios guardados exitosamente en CSV\n");
        } else {
            updateConsola("✗ Error al guardar CSV\n");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void botonEliminarDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarDocumentoActionPerformed
        String username = JOptionPane.showInputDialog(this, "Nombre del usuario:");
        if (username == null) {
            JOptionPane.showMessageDialog(this, "Error: Debe colocar un nombre.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        username = Normalizador.NormalizarTexto(username);
        Usuario usuarioExistente = (Usuario) logica.getUsuariosLocal().get(username);
        if (usuarioExistente == null) {
            JOptionPane.showMessageDialog(this, "Error: El usuario '" + username + "' no existe.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String docname = JOptionPane.showInputDialog(this, "Nombre del documento:");
        docname = Normalizador.NormalizarTexto(docname);
        documento doc = usuarioExistente.buscar(docname);

        if (doc != null) {
            boolean exito = usuarioExistente.eliminarDocumento(docname);
            if (exito) {
                logica.eliminarDocumentoUI(username, doc); // Cambio aquí
                updateConsola("✓ Documento " + docname + " eliminado.\n");
                JOptionPane.showMessageDialog(this, "Documento eliminado.");
            } else {
                updateConsola("✗ Error al eliminar documento.\n");
            }
        } else {
            JOptionPane.showMessageDialog(this, "No se encontró el documento.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonEliminarDocumentoActionPerformed

    private void botonEliminarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarUsuarioActionPerformed
        String username = JOptionPane.showInputDialog(this, "Nombre del usuario:");
        if (username == null) { //se añade esto por si acaso el usuario escapa
            JOptionPane.showMessageDialog(this, "Error: Debe colocar un nombre.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        username = Normalizador.NormalizarTexto(username);
        Usuario usuarioExistente = (Usuario) logica.getUsuariosLocal().get(username);
        if (usuarioExistente == null) {
            JOptionPane.showMessageDialog(this, "Error: El usuario '" + username + "' no existe.", "Usuario no encontrado", JOptionPane.ERROR_MESSAGE);
            return;
        }
        else
        {
            logica.eliminarUsuarioUI(usuarioExistente);
        }
        
    }//GEN-LAST:event_botonEliminarUsuarioActionPerformed


    public void updateConsola(String input) {
        output.setText("");
        output.append(input);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(InterfazGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> {
            new InterfazGrafica().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAddUser;
    private javax.swing.JButton botonAnadirDoc;
    private javax.swing.JButton botonEliminarDocumento;
    private javax.swing.JButton botonEliminarUsuario;
    private javax.swing.JButton botonMostrarCola;
    private javax.swing.JButton botonMostrarUser;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea output;
    // End of variables declaration//GEN-END:variables
}
