package interfaznew;

import clases.Usuario;
import primitivas.GuardadoCSV;
import clases.Documento;
import javax.swing.JOptionPane;
import clases.Impresion;
import org.graphstream.graph.Graph;
import org.graphstream.graph.Node;
import org.graphstream.graph.implementations.SingleGraph;
import org.graphstream.ui.spriteManager.SpriteManager;
import org.graphstream.ui.view.Viewer;
import primitivas.Lista;
import proyecto2edd.Simulador;
import primitivas.Normalizador;

/**
 *
 * @author miwindowspc
 */
public class InterfazGrafica extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InterfazGrafica.class.getName());
    private Simulador motor;
    private LogicaInterfaz logica;

    /**
     * Creates new form InterfazGrafica
     */
    public InterfazGrafica() {
        this.motor = new Simulador();
        this.logica = new LogicaInterfaz(this, this.motor);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonMostrarCola = new javax.swing.JButton();
        botonAddUser = new javax.swing.JButton();
        botonMostrarUser = new javax.swing.JButton();
        botonAnadirDoc = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        output = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        botonEliminarDocumento = new javax.swing.JButton();
        botonEliminarUsuario = new javax.swing.JButton();
        botonAnadirCola = new javax.swing.JButton();
        labelReloj = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        botonMostrarColaArbol = new javax.swing.JButton();
        botonImprimirUltimo = new javax.swing.JButton();
        botonEliminarCola = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botonMostrarCola.setText("Mostrar Cola Simple");
        botonMostrarCola.addActionListener(this::botonMostrarColaActionPerformed);

        botonAddUser.setText("Añadir Usuario");
        botonAddUser.addActionListener(this::botonAddUserActionPerformed);

        botonMostrarUser.setText("Mostrar Users");
        botonMostrarUser.addActionListener(this::botonMostrarUserActionPerformed);

        botonAnadirDoc.setText("Añadir Documento");
        botonAnadirDoc.addActionListener(this::botonAnadirDocActionPerformed);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setText("Pila de Impresión");

        output.setColumns(20);
        output.setRows(5);
        jScrollPane1.setViewportView(output);

        jButton1.setText("Cargar CSV");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("Guardar CSV");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        botonEliminarDocumento.setText("Eliminar Documento");
        botonEliminarDocumento.addActionListener(this::botonEliminarDocumentoActionPerformed);

        botonEliminarUsuario.setText("Eliminar Usuario");
        botonEliminarUsuario.addActionListener(this::botonEliminarUsuarioActionPerformed);

        botonAnadirCola.setText("Añadir A Cola");
        botonAnadirCola.addActionListener(this::botonAnadirColaActionPerformed);

        labelReloj.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelReloj.setForeground(new java.awt.Color(120, 0, 0));
        labelReloj.setText("1");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel2.setText("Reloj:");

        botonMostrarColaArbol.setText("Mostrar Cola Arbol");
        botonMostrarColaArbol.addActionListener(this::botonMostrarColaArbolActionPerformed);

        botonImprimirUltimo.setText("Imprimir 1ro en Cola");
        botonImprimirUltimo.addActionListener(this::botonImprimirUltimoActionPerformed);

        botonEliminarCola.setText("Eliminar de Cola");
        botonEliminarCola.addActionListener(this::botonEliminarColaActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelReloj)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(botonMostrarColaArbol))
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonMostrarUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonMostrarCola, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(302, 302, 302)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(botonAnadirDoc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(botonEliminarDocumento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(botonEliminarUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addComponent(botonAnadirCola, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(botonImprimirUltimo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(75, 75, 75)
                                .addComponent(botonAddUser, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(botonEliminarCola, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(226, 226, 226)))))
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(labelReloj)
                    .addComponent(jLabel2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(botonMostrarCola)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(botonAddUser))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(botonMostrarColaArbol)
                                    .addComponent(botonImprimirUltimo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(botonEliminarCola, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonAnadirCola)
                            .addComponent(botonMostrarUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(38, 38, 38))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(botonAnadirDoc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonEliminarDocumento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(botonEliminarUsuario))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonMostrarColaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMostrarColaActionPerformed
        Lista<Impresion> colaOrdenada = motor.getColaOrdenadaParaUI();
        logica.refrescarColaUI(colaOrdenada);
        logica.mostrarVentanaCola();
    }//GEN-LAST:event_botonMostrarColaActionPerformed

    private void botonAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAddUserActionPerformed
        String nombre = JOptionPane.showInputDialog(this, "Nombre del usuario:");
        if (nombre != null && !nombre.trim().isEmpty()) {
            nombre = Normalizador.NormalizarTexto(nombre);
            String[] opciones = {"Prioridad Alta", "Prioridad Media", "Prioridad Baja"};
            int seleccion = JOptionPane.showOptionDialog(this,
                    "¿Qué prioridad desea que tenga este usuario?",
                    "Escoger Prioridad",
                    JOptionPane.DEFAULT_OPTION,
                    JOptionPane.QUESTION_MESSAGE,
                    null,
                    opciones,
                    opciones[0]);

            String prioridad = "";
            switch (seleccion) {
                case 0: {
                    prioridad = "prioridad_alta";
                    break;
                }

                case 1: {
                    prioridad = "prioridad_media";
                    break;
                }

                case 2: {
                    prioridad = "prioridad_baja";
                    break;
                }
                default: {
                    return;
                }
            }
            boolean exito = logica.intentarRegistrarUsuario(nombre, prioridad);
            if (exito) {
                Usuario nuevo = new Usuario(nombre, prioridad);
                logica.AñadirUsuarioUI(nuevo);
                updateConsola("✓ Usuario '" + nombre + "' añadido correctamente.\n");
                JOptionPane.showMessageDialog(this, "Usuario registrado con éxito.");
            } else {
                updateConsola("✗ Error: El usuario '" + nombre + "' ya existe en el sistema.\n");
                JOptionPane.showMessageDialog(this, "Ese usuario ya existe.", "Error de Duplicado", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            updateConsola("✗ Error: No puede poner un nombre vacio a un usuario.");
            JOptionPane.showMessageDialog(this, "No puede pasar un usuario vacio.", "Error de Nombre", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_botonAddUserActionPerformed

    private void botonMostrarUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMostrarUserActionPerformed
        logica.mostrarVentanaUser();
    }//GEN-LAST:event_botonMostrarUserActionPerformed

    private void botonAnadirDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAnadirDocActionPerformed
        //FALTA: integrar logica de guardado
        String username = JOptionPane.showInputDialog(this, "Nombre del usuario:");
        if (username == null) { //se añade esto por si acaso el usuario escapa
            return;
        }
        username = Normalizador.NormalizarTexto(username);
        Usuario usuarioExistente = (Usuario) logica.getUsuariosLocal().get(username);

        if (usuarioExistente == null) {
            JOptionPane.showMessageDialog(this, "Error: El usuario '" + username + "' no existe.", "Usuario no encontrado", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String docname = JOptionPane.showInputDialog(this, "Nombre del documento:");
        docname = Normalizador.NormalizarTexto(docname);
        if (usuarioExistente.buscar(docname) == null) {
            String paginasS = JOptionPane.showInputDialog(this, "Cantidad de paginas:");

            if (paginasS != null) {
                if (paginasS.matches("^[0-9]*$") && !paginasS.isEmpty()) { //se revisa si el string tiene los numeros validos y si no esta vacio
                    int paginas = Integer.parseInt(paginasS);
                    if (paginas > 0) { //luego se verifica si la cantidad de paginas es mayor a 0
                        String tipo = JOptionPane.showInputDialog(this, "Tipo de documento:");
                        Documento doc = new Documento(docname, paginas, tipo, false);
                        logica.AnadirDocumentoUser(username, doc);
                    } else {
                        JOptionPane.showMessageDialog(this, "La cantidad de páginas debe ser mayor a 0.", "ERROR", JOptionPane.ERROR_MESSAGE);
                        updateConsola("✗ Error al añadir documento: La cantidad de paginas debe ser mayor a 0.\n");
                    }
                } else {
                    javax.swing.JOptionPane.showMessageDialog(null,
                            "Eso no es un numero valido.",
                            "ERROR",
                            javax.swing.JOptionPane.ERROR_MESSAGE);
                    updateConsola("✗ Error al añadir documento: El numero de paginas no es valido.\n");
                }
            } else {
                javax.swing.JOptionPane.showMessageDialog(null,
                        "No insertaste un nombre al documento.",
                        "ERROR",
                        javax.swing.JOptionPane.ERROR_MESSAGE);
                updateConsola("✗ Error al añadir documento: No se inserto un nombre.\n");
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(null,
                    "Ese documento ya existe.",
                    "ERROR",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            updateConsola("✗ Error al añadir documento: Ya existe ese documento.\n");
        }
    }//GEN-LAST:event_botonAnadirDocActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        boolean exito = logica.cargarUsuariosDesdeCSV();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        boolean exito = logica.guardarUsuariosEnCSV();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void botonEliminarDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarDocumentoActionPerformed
        String username = JOptionPane.showInputDialog(this, "Nombre del usuario:");
        if (username == null) {
            JOptionPane.showMessageDialog(this, "Error: Debe colocar un nombre.", "Error", JOptionPane.ERROR_MESSAGE);
            updateConsola("✗ Error: Debe colocar un nombre.\n");
            return;
        }
        
        username = Normalizador.NormalizarTexto(username);
        Usuario usuarioExistente = (Usuario) logica.getUsuariosLocal().get(username);
        if (usuarioExistente == null) {
            JOptionPane.showMessageDialog(this, "Error: El usuario '" + username + "' no existe.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String docname = JOptionPane.showInputDialog(this, "Nombre del documento:");
        docname = Normalizador.NormalizarTexto(docname);
        Documento doc = usuarioExistente.buscar(docname);

        if (doc != null) {
            boolean exito = usuarioExistente.eliminarDocumento(docname);
            if (exito) {
                logica.eliminarDocumentoUI(username, doc); // Cambio aquí
                updateConsola("✓ Documento " + docname + " eliminado.\n");
                JOptionPane.showMessageDialog(this, "Documento eliminado.");
            } else {
                updateConsola("✗ No se pudo elimiinar el documento, esta en cola.\n");
            }
        } else {
            JOptionPane.showMessageDialog(this, "No se encontró el documento.", "Error", JOptionPane.ERROR_MESSAGE);
            updateConsola("✗ Error: No se encontro el documento para eliminar.\n");
        }
    }//GEN-LAST:event_botonEliminarDocumentoActionPerformed

    private void botonEliminarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarUsuarioActionPerformed
        String username = JOptionPane.showInputDialog(this, "Nombre del usuario:");
        if (username == null) { //se añade esto por si acaso el usuario escapa
            JOptionPane.showMessageDialog(this, "Error: Debe colocar un nombre.", "Error", JOptionPane.ERROR_MESSAGE);
            updateConsola("✗ Error: Debe colocar un nombre.\n");
            return;
        }
        username = Normalizador.NormalizarTexto(username);
        Usuario usuarioExistente = (Usuario) logica.getUsuariosLocal().get(username);
        if (usuarioExistente == null) {
            JOptionPane.showMessageDialog(this, "Error: El usuario '" + username + "' no existe.", "Usuario no encontrado", JOptionPane.ERROR_MESSAGE);
            updateConsola("✗ No se pudo elimiinar el usuario, no existe.\n");
            return;
        } else {
            logica.eliminarUsuarioUI(usuarioExistente);
            motor.eliminarUsuario(username);
        }

    }//GEN-LAST:event_botonEliminarUsuarioActionPerformed

    private void botonAnadirColaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAnadirColaActionPerformed
        String username = JOptionPane.showInputDialog(this, "Nombre del usuario:");
        if (username == null) {
            JOptionPane.showMessageDialog(this, "Error: Debe colocar un nombre.", "Error", JOptionPane.ERROR_MESSAGE);
            updateConsola("✗ Error: Debe colocar un nombre.\n");
            return;
        }
        username = Normalizador.NormalizarTexto(username);
        Usuario usuarioExistente = (Usuario) logica.getUsuariosLocal().get(username);
        if (usuarioExistente == null) {
            JOptionPane.showMessageDialog(this, "Error: El usuario '" + username + "' no existe.", "Usuario no encontrado", JOptionPane.ERROR_MESSAGE);
            return;
        } else {
            String docname = JOptionPane.showInputDialog(this, "Nombre del documento:");
            if (docname == null) {
                JOptionPane.showMessageDialog(this, "Error: Debe colocar un nombre.", "Error", JOptionPane.ERROR_MESSAGE);
                updateConsola("✗ Error: Debe colocar un nombre.\n");
                return;
            }
            docname = Normalizador.NormalizarTexto(docname);
            Documento doc = usuarioExistente.buscar(docname);
            if (doc != null) {
                if (!doc.isEncola()) {
                    String[] opciones = {"Si es Prioritario", "No es Prioritario"};
                    int seleccion = JOptionPane.showOptionDialog(this,
                            "¿Este documento es prioritario?",
                            "Escoger Prioridad",
                            JOptionPane.DEFAULT_OPTION,
                            JOptionPane.QUESTION_MESSAGE,
                            null,
                            opciones,
                            opciones[0]);

                    boolean prioritario = false;
                    switch (seleccion) {
                        case 0: {
                            prioritario = true;
                            break;
                        }

                        case 1: {
                            prioritario = false;
                            break;
                        }
                        default: {
                            return;
                        }
                    }
                    Impresion imp = motor.enviarACola(usuarioExistente, doc, motor.getReloj(), prioritario);
                    doc.setEncola(true);
                    motor.tic();
                    ActualizarReloj();
                    logica.agregarAColaUI(imp);
                    logica.refrescarColaUI(motor.getColaOrdenadaParaUI());
                    updateConsola("✓ Documento añadido a la cola exitosamente.\n");
                }
                else
                {
                     JOptionPane.showMessageDialog(this, "Este documento ya esta en cola.", "Advertencia", JOptionPane.WARNING_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Error: No se encontro el documento en el usuario.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }

    }//GEN-LAST:event_botonAnadirColaActionPerformed

    private void botonMostrarColaArbolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMostrarColaArbolActionPerformed
        logica.refrescarColaArbolUI();
        logica.mostrarVentanaColaArbol();
    }//GEN-LAST:event_botonMostrarColaArbolActionPerformed

    private void botonImprimirUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonImprimirUltimoActionPerformed
        Impresion elim = motor.liberarImpresora();
        if (elim == null)
        {
            JOptionPane.showMessageDialog(this, "Error: La cola esta vacia.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        else
        {
            motor.tic();
            ActualizarReloj();
             updateConsola("✓ Elemento de mayor prioridad impreso, " + elim.getDoc().getNombre() + " ha sido impreso.\n");
        }
    }//GEN-LAST:event_botonImprimirUltimoActionPerformed

    private void botonEliminarColaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarColaActionPerformed
        String username = JOptionPane.showInputDialog(this, "Nombre del usuario:");
        if (username == null) {
            JOptionPane.showMessageDialog(this, "Error: Debe colocar un nombre.", "Error", JOptionPane.ERROR_MESSAGE);
            updateConsola("✗ Error: Debe colocar un nombre.\n");
            return;
        }
        username = Normalizador.NormalizarTexto(username);
        Usuario usuarioExistente = (Usuario) logica.getUsuariosLocal().get(username);
        if (usuarioExistente == null) {
            JOptionPane.showMessageDialog(this, "Error: El usuario '" + username + "' no existe.", "Usuario no encontrado", JOptionPane.ERROR_MESSAGE);
            return;
        } 
        else {
            String docname = JOptionPane.showInputDialog(this, "Nombre del documento:");
            if (docname == null) {
                JOptionPane.showMessageDialog(this, "Error: Debe colocar un nombre.", "Error", JOptionPane.ERROR_MESSAGE);
                updateConsola("✗ Error: Debe colocar un nombre.\n");
                return;
            }
            docname = Normalizador.NormalizarTexto(docname);
            Documento doc = usuarioExistente.buscar(docname);
            if (doc != null) {
                boolean exito = motor.eliminarDocumentoDeCola(username, doc);
                if (exito)
                {
                    updateConsola("✓ Documento de nombre " + docname + " ha sido eliminado de la cola.\n");
                }
                else{
                    updateConsola("✗ Error: La cola parece estar vacia.\n");
                }
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Error: El usuario '" + username + "' no existe.", "Usuario no encontrado", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
    }//GEN-LAST:event_botonEliminarColaActionPerformed

    public void updateConsola(String input) {
        output.setText("");
        output.append(input);
    }
    
    public void ActualizarReloj()
    {
        labelReloj.setText(String.valueOf(motor.getReloj()));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(InterfazGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> {
            new InterfazGrafica().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAddUser;
    private javax.swing.JButton botonAnadirCola;
    private javax.swing.JButton botonAnadirDoc;
    private javax.swing.JButton botonEliminarCola;
    private javax.swing.JButton botonEliminarDocumento;
    private javax.swing.JButton botonEliminarUsuario;
    private javax.swing.JButton botonImprimirUltimo;
    private javax.swing.JButton botonMostrarCola;
    private javax.swing.JButton botonMostrarColaArbol;
    private javax.swing.JButton botonMostrarUser;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelReloj;
    private javax.swing.JTextArea output;
    // End of variables declaration//GEN-END:variables
}
